### ISSUE TITLE
"Feedback Request Endpoint" wiki is missing request schema

### ISSUE THREAD

**Issue by johnGachihi** [droidconKE/droidconKE2022Android#115]
The [Feedback Request Endpoint](https://github.com/droidconKE/droidconKE2022Android/wiki/Feedback-Request-Endpoint) wiki doesn't have a schema or example of the request the endpoint expects.
What's under "REQUEST BODY" looks like a response example.

**Comment by wangerekaharun** [comment]
Hi @johnGachihi the first part shows the request you're supposed to send.

**Comment by johnGachihi** [comment]
Yes, I've seen it.
It wasn't there initially though. Thank you, silent updater :smile:

**Comment by johnGachihi** [comment]
Unrelated question: Is the feedback for the whole event or for a particular session? The endpoint URL suggests it's for a session (`.../feedback/sessions/android-architecture-1584106972`) but the mockups suggest it's for the whole event.

**Comment by MamboBryan** [comment]
@johnGachihi, @wangerekaharun is this issue resolved we close it?

**Comment by johnGachihi** [comment]
Yes, we can close it @MamboBryan
