### ISSUE TITLE
Implement Speaker UI Screen 

### ISSUE THREAD

**Issue by Mohameddekow** [droidconKE/droidconKE2022Android#31]
Hey @chepsi allow me to design the speaker's screen UI

_Originally posted by @Mohameddekow in https://github.com/droidconKE/droidconKE2022Android/issues/18#issuecomment-1185517050_

**Comment by chepsi** [comment]
@Mohameddekow Please feel free. Work on the UI and ViewModel to ensure the PR is small.

**Comment by Mohameddekow** [comment]
oooh cool

**Comment by chepsi** [comment]
@Mohameddekow Please assign yourself this task in trello board. https://trello.com/b/DNGPH3Ui/droidconke22-android-app

**Comment by Mohameddekow** [comment]
@chepsi great request sent 👍

**Comment by chepsi** [comment]
Closing this in favor of the trello board.
