### ISSUE TITLE
[UI] Implement sessions card 

### ISSUE THREAD

**Issue by Kagiri11** [droidconKE/droidconKE2022Android#38]
**Is your feature request related to a problem? Please describe.**
Hey team, I am requesting to create the sessions card

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kibettheophilus** [comment]
@Kagiri11 you can work on it, I have added to [Trello](https://trello.com/c/GVDBkDi3/24-uisessions-card)

**Comment by dis-jointed** [comment]
Hey team, can you add me in trello I see the app designs

**Comment by chepsi** [comment]
https://trello.com/invite/b/DNGPH3Ui/a2f180658663b8bb0aa7644cbdc62503/droidconke22-android-app

**Comment by chepsi** [comment]
Closing this in favor of the trello board.
